project_id = "xvgermmegyipzmiwewzo"

[functions.create-user]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.check-pdi-deadlines]
verify_jwt = false

[functions.hotmart-sync]
verify_jwt = false

[functions.asaas-sync]
verify_jwt = false

[functions.quiz-ai-diagnosis]
verify_jwt = false
